### ISSUE TITLE
Ghidra Headless Analysis Failure: No JSON object could be decoded

### ISSUE THREAD

**Issue by Zorro9999** [Cisco-Talos/GhIDA#19]
Good day. There is a problem as described above. Here is the log from Ida Pro.
```
  bytes   pages size description
--------- ----- ---- --------------------------------------------
   262144    32 8192 allocating memory for b-tree...
    65536     8 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...
-----------------------------------------------------------------
   589824            total memory allocated

Loading processor module C:\Program Files\IDA 7.2\procs\i5164.dll for 8051...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
Database for file '307.bin' has been loaded.
============================================================
GhIDA Decompiler v0.1
Andrea Marcelli <anmarcel@cisco.com>
Cisco Talos, June 2019
GhIDA Decompiler shortcut key is Ctrl-Alt-D
============================================================
GhIDA:: [DEBUG] Reading GhIDA configuration
('GHIDA_CONF.load_save_cached_code', False)
('GHIDA_CONF.load_save_cached_comments', False)
GhIDA:: [DEBUG] code_cache_path: c:\users\user\appdata\local\temp\decompiled_cache_FE46C519975BC6E312BB1719D93A0A64.json
GhIDA:: [DEBUG] comments_cache_path: c:\users\user\appdata\local\temp\comments_cache_FE46C519975BC6E312BB1719D93A0A64.json
GhIDA:: [DEBUG] Registering handlers
GhIDA [DEBUG] ScreenEAHook initialized
---------------------------------------------------------------------------------------------
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
GhIDA:: [DEBUG] DisasmsHandler HELLO
('GHIDA_CONF.global_settings', True)
('GHIDA_CONF.use_ghidra_server', False)
('GHIDA_CONF.ghidra_install_path', 'E:\\ghidra_9.1.2_PUBLIC_20200212\\ghidra_9.1.2_PUBLIC')
('GHIDA_CONF.ghidra_server_url', 'http://localhost:8080/ghidra/api')
('GHIDA_CONF.show_settings', True)
('GHIDA_CONF.load_save_cached_code', False)
('GHIDA_CONF.load_save_cached_comments', False)
GhIDA:: [INFO] Configuration saved to c:\users\user\appdata\local\temp\ghida_config.json
GhIDA:: [DEBUG] EXPORT_XML_FILE: True
GhIDA:: [DEBUG] Exporting IDA project into XML format

XML Exporter v5.0.1 : SDK 720
-----------------------------------------------------------
Exporting XML <PROGRAM> document ....
Processing PROGRAM                 GhIDA:: [DEBUG] compiler name: Unknown
GhIDA:: [DEBUG] new_compiler_name: default
CPU time: 0.0019
Processing MEMORY_MAP              CPU time: 0.0061
Processing CODE                    CPU time: 0.0013
Processing DATA                    CPU time: 0.0507
Processing COMMENTS                CPU time: 0.0032
Processing PROGRAM_ENTRY_POINTS    CPU time: 0.0005
Processing SYMBOL_TABLE            CPU time: 0.0023
Processing FUNCTIONS               CPU time: 0.0041
Processing MARKUP                  CPU time: 0.0275
                             Total CPU time: 0.4666
--------------------------------------
PROGRAM                           1
INFO_SOURCE                       1
PROCESSOR                         1
COMPILER                          1
MEMORY_MAP                        1
MEMORY_SECTION                    4
MEMORY_CONTENTS                   2
CODE                              1
CODE_BLOCK                        9
DATA                              1
DEFINED_DATA                     62
TYPEINFO_CMT                    109
COMMENTS                          1
COMMENT                          27
PROGRAM_ENTRY_POINTS              1
PROGRAM_ENTRY_POINT               8
SYMBOL_TABLE                      1
SYMBOL                           29
FUNCTIONS                         1
FUNCTION                         50
ADDRESS_RANGE                    60
REPEATABLE_CMT                    7
MARKUP                            1
--------------------------------------
Total XML Elements:             379
Database exported to: E:\RABOTA\FE46C519975BC6E312BB1719D93A0A64_vnzEm.xml
GhIDA:: [DEBUG] found 0 symbols
GhIDA:: [INFO] XML exporting completed
GhIDA:: [DEBUG] decompiled cache miss (432)
GhIDA:: [DEBUG] Decompiling 432
GhIDA:: [DEBUG] EXPORT_XML_FILE: False
GhIDA:: [INFO] Ghidra headless (timeout: 1000s)
GhIDA:: [INFO] Waiting Ghidra headless analysis to finish...
GhIDA:: [INFO] Ghidra analysis completed!
GhIDA:: [!] No JSON object could be decoded
GhIDA:: [!] Ghidra headless analysis failed
GhIDA:: [!] Decompilation interrupted.

```

With what it can be connected ? Incorrect compiler or Something is missing from my installation. The thing is that if I upload it directly through the hydra, then the file will decompile, but you must explicitly indicate where the code is in this file.

**Comment by cq674350529** [comment]
@jimmy-sonny Thanks for your awesome work on this plugin.

I came across the same issue "Ghidra Headless Analysis Failure: No JSON object could be decoded".  I wanted to decompile the mips binary with this plugin, and the related environment is：`win10`, `IDA Pro 7.0`, `python 2.7`, and with a local installation of Ghidra。

Finally I solved the issue in my case, here are some steps I have tried. @Zorro9999 Maybe you can learn from it.
1. run the `FunctionDecompile.py` in Ghidra directly  --->  it works well
2. run the ghidra related cmd (`analyzeHeadless.bat xxx`) in console directly  ---> it failed, according to the error, I added the `-processor <languageID>` option and made it work in my case
3. change `subprocess.Popen()` in `ghidra_plugin/lib.py` to `subprocess.call()`and the pass the `cmd` args as a string  ---> it works

I found the call to `subprocess.Popen.poll(p)` will set returncode immediately even if the child process doesn't finish in the original way.  As a result, no json file will be generated, which may be the root casue of this issue.

After looking the [docs](https://docs.python.org/2/library/subprocess.html#subprocess.Popen) of `subprocess`, I found the folllow description:
> The shell argument (which defaults to False) specifies whether to use the shell as the program to execute. If shell is True, it is recommended to pass args as a string rather than as a sequence.

Since my env is `win10`, the `shell` is set to `True`. So I pass the `cmd` args as s string and it works finally.

https://github.com/Cisco-Talos/GhIDA/blob/d153e0dddf437b96dbbcd9be23774a538f614317/ghida_plugin/lib.py#L239-L252

In summay, I make the following changes to make it work on my case.
+ add `-processor <languageID>` option
+ wrap `path` in quotes in case it contains spaces
+ pass the `cmd` args as a string if `shell=True`

```python
cmd = ['"%s"' % ghidra_headless_path,
        ".",
        "Temp",
        "-import",
        '"%s"' % xml_file_path,
        '-readOnly',
        '-scriptPath',
        '"%s"' % ghidra_plugins_path,
        '-postScript',
        'FunctionDecompile.py',
        address,
        '"%s"' % output_path,
        "-noanalysis",
        "-deleteProject",
        "-processor",
        '"%s"' % processor]

# Options to 'safely' terminate the process
if os.name == 'posix':
    kwargs = {
        'preexec_fn': os.setsid
    }
else:
    kwargs = {
        'creationflags': subprocess.CREATE_NEW_PROCESS_GROUP,
        'shell': True
    }
    cmd = ' '.join(cmd)

p = subprocess.Popen(cmd,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT,
                        **kwargs)
```

**Comment by Zorro9999** [comment]
Good evening. Changed according to your settings. I began to create an XML file and a code file in the folder, but then stop.
""
Total XML Elements:             666
Database exported to: A8E703B551892D73C6BB9E989C60_YuZGb.xml
GhIDA:: [DEBUG] found 0 symbols
GhIDA:: [INFO] XML exporting completed
GhIDA:: [DEBUG] decompiled cache miss (a50)
GhIDA:: [DEBUG] Decompiling a50
GhIDA:: [DEBUG] EXPORT_XML_FILE: False
GhIDA:: [!] global name 'processor' is not defined
GhIDA:: [!] Ghidra headless analysis failed
GhIDA:: [!] Decompilation interrupted.
""

**Comment by cq674350529** [comment]
@Zorro9999 If the arch of your binary is `x86` or `x64` (supported by `GhIDA` Plugin in default), you can remove the added `-processor` option. Otherwise, you have to provide the proper `processor` arg, which is not handled by GhIDA plugin in default.

In my case, I only handle the mips arch automatically. Maybe you can specify it manually first to test if it works. Here is the related information copied from the `ghidra_x.x/support/analyzeHeadlessREADME.html#processor`.

![image](https://user-images.githubusercontent.com/13868458/87107383-36492b00-c292-11ea-983a-5accb1457ede.png)

In my case, the `processor` arg is `MIPS:BE:32:default`. You have to find your own.

**Comment by Zorro9999** [comment]
@cq674350529 cq674350529 Thank you for responding to my problem. I’ll tell you what I did, as you wrote above, I edited the lib.py file according to the example. The plugin began to swear that it does not know this type of processor, where should I indicate it in the code? I don’t understand this. In the output xml file it looks like this: <PROCESSOR NAME = "8051" ADDRESS_MODEL = "32-bit" ENDIAN = "big" />

**Comment by cq674350529** [comment]
@Zorro9999 To test it quickly, you can manually specify the `processor` arg like the following。

```python
cmd = ['"%s"' % ghidra_headless_path,
        ".",
        "Temp",
        "-import",
        '"%s"' % xml_file_path,
        '-readOnly',
        '-scriptPath',
        '"%s"' % ghidra_plugins_path,
        '-postScript',
        'FunctionDecompile.py',
        address,
        '"%s"' % output_path,
        "-noanalysis",
        "-deleteProject",
        "-processor",
        "<processor here>"]    // <=== here
```

According to the output.xml above, I'm not sure if the ghidra supports it or not. I can't find the `8051:BE:32:default`, maybe you can try `8051:BE:16:default`. You can try to load your binary with `ghidra` first. If it works, then you can get the processor info in ghidra dialog box.

By the way, I can test it if it's possible for you to upload the binary.

**Comment by Zorro9999** [comment]
@cq674350529 You are the best .. Thank you so much. Earned and decompiled correctly.

**Comment by jimmy-sonny** [comment]
Dear @cq674350529 and @Zorro9999, I'm sorry for the very late answer. Thanks for your contributions on how to improve the usage of `subprocess` and how to support other architectures. I'll make some additional tests and I'll include them in a future release.
